image: continuumio/miniconda3:latest

stages:
  - build
  - test

install:
  stage: build
  script: 
    - apt-get update -q -y
    - apt-get install -y build-essential
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a

    - conda env create -f nr_fano_env.yml
    - conda activate nr_fano 

unittest:
   stage: test
   before_script: 
     - cd paper_notebooks
     - conda activate nr_fano
   script:
     - py.test
